### ISSUE TITLE
TypeError: this.$el.querySelector is not a function

### ISSUE THREAD

**Issue by emichristiansen** [yariksav/bootstrap-vue-dialog#2]
Hi, I'm seeing this error in my console. I thought I was doing something wrong, but then I checked in the example page and the same error is showing up with all the Dialog modals.

**Comment by giorgi-ghviniashvili** [comment]
I am having same issue. It tries to find `.modal-backdrop` inside the modal container, while modal is appended to the document.body (outside the modal container), so as a result it can not find the modal-backdrop and resulting the error. 

line 47 in DialodLayout.vue causes this error.
